version: "3.8"
services:
  sh-master:
    ports:
      - "8000:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: sh-master
    hostname: sh-master
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.1
  sh-01:
    ports:
      - "8001:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: sh-01
    hostname: sh-01
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.2
  sh-02:
    ports:
      - "8002:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: sh-02
    hostname: sh-02
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.3
  indx-master:
    ports:
      - "8003:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: indx-master
    hostname: indx-master
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.4
  idx-01:
    ports:
      - "8004:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: idx-01
    hostname: idx-01
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.5
  idx-02:
    ports:
      - "8005:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: idx-02
    hostname: idx-02
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.6
  deployer:
    ports:
      - "8006:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license
    image: "splunk/splunk"
    container_name: deployer
    hostname: deployer
    networks:
      learning_splunk:
        ipv4_address: 172.28.1.7
networks:
  learning_splunk:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
